.TH "Charts" 3 "DAVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Charts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAverage_Chart\fP"
.br
.ti -1c
.RI "class \fBChart\fP"
.br
.ti -1c
.RI "class \fBLine_Chart\fP"
.br
.ti -1c
.RI "class \fBLine_Chart_of_specific_Type\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DAVA from the source code\&.
