.TH "D:/Katerina/data-visualisation-and-analysis-app/data.py" 3 "DAVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Katerina/data-visualisation-and-analysis-app/data.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdata\&.CamerasData\fP"
.br
.ti -1c
.RI "class \fBdata\&.Data\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdata\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBdata\&.USER\fP = 'sqluser'"
.br
.ti -1c
.RI "str \fBdata\&.PASSWORD\fP = 'Chroma1\&.0'"
.br
.ti -1c
.RI "str \fBdata\&.HOST\fP = '192\&.168\&.86\&.12'"
.br
.ti -1c
.RI "int \fBdata\&.PORT\fP = 3306"
.br
.ti -1c
.RI "str \fBdata\&.DATABASE\fP = 'production_data'"
.br
.ti -1c
.RI "\fBdata\&.CONNECTION\fP = create_engine(url='mysql+pymysql://{0}:{1}@{2}:{3}/{4}'\&.format(\fBUSER\fP, \fBPASSWORD\fP, \fBHOST\fP, \fBPORT\fP, \fBDATABASE\fP))"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DAVA from the source code\&.
