.TH "data" 3 "DAVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamerasData\fP"
.br
.ti -1c
.RI "class \fBData\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBUSER\fP = 'sqluser'"
.br
.ti -1c
.RI "str \fBPASSWORD\fP = 'Chroma1\&.0'"
.br
.ti -1c
.RI "str \fBHOST\fP = '192\&.168\&.86\&.12'"
.br
.ti -1c
.RI "int \fBPORT\fP = 3306"
.br
.ti -1c
.RI "str \fBDATABASE\fP = 'production_data'"
.br
.ti -1c
.RI "\fBCONNECTION\fP = create_engine(url='mysql+pymysql://{0}:{1}@{2}:{3}/{4}'\&.format(\fBUSER\fP, \fBPASSWORD\fP, \fBHOST\fP, \fBPORT\fP, \fBDATABASE\fP))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "data\&.CONNECTION = create_engine(url='mysql+pymysql://{0}:{1}@{2}:{3}/{4}'\&.format(\fBUSER\fP, \fBPASSWORD\fP, \fBHOST\fP, \fBPORT\fP, \fBDATABASE\fP))"

.SS "str data\&.DATABASE = 'production_data'"

.SS "str data\&.HOST = '192\&.168\&.86\&.12'"

.SS "str data\&.PASSWORD = 'Chroma1\&.0'"

.SS "int data\&.PORT = 3306"

.SS "str data\&.USER = 'sqluser'"

.SH "Author"
.PP 
Generated automatically by Doxygen for DAVA from the source code\&.
