.TH "data.CamerasData" 3 "DAVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data.CamerasData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget_cameras_name\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
The CamerasData class have:

           Methods:
              get_cameras_name() : Function that return numpy\&.ndarray with the names of the cameras\&.
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "data\&.CamerasData\&.get_cameras_name ( self)"

.PP
.nf
    get_cameras_name()
    Function that return numpy\&.ndarray with the names of the cameras\&.

    Returns:
        cameras_name\&.values (numpy\&.ndarray)

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for DAVA from the source code\&.
