.TH "D:/Katerina/data-visualisation-and-analysis-app/mainWindow.py" 3 "DAVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Katerina/data-visualisation-and-analysis-app/mainWindow.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmainWindow\&.MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmainWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DAVA from the source code\&.
