.TH "ui_mainwindow.Ui_MainWindow" 3 "DAVA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_mainwindow.Ui_MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.PP
Inherited by \fBmainWindow\&.MainWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetupUi\fP (self, MainWindow)"
.br
.ti -1c
.RI "\fBretranslateUi\fP (self, MainWindow)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout\fP"
.br
.ti -1c
.RI "\fBframe_7\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_2\fP"
.br
.ti -1c
.RI "\fBframe_2\fP"
.br
.ti -1c
.RI "\fBverticalLayout_2\fP"
.br
.ti -1c
.RI "\fBframe\fP"
.br
.ti -1c
.RI "\fBformLayout_2\fP"
.br
.ti -1c
.RI "\fBgroupBox_period\fP"
.br
.ti -1c
.RI "\fBformLayout\fP"
.br
.ti -1c
.RI "\fBlabel_from\fP"
.br
.ti -1c
.RI "\fBdateEdit_from\fP"
.br
.ti -1c
.RI "\fBlabel_to\fP"
.br
.ti -1c
.RI "\fBdateEdit_to\fP"
.br
.ti -1c
.RI "\fBframe_3\fP"
.br
.ti -1c
.RI "\fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBgroupBox_selec_camera\fP"
.br
.ti -1c
.RI "\fBverticalLayout_3\fP"
.br
.ti -1c
.RI "\fBcomboBox_camera\fP"
.br
.ti -1c
.RI "\fBgroupBox_options\fP"
.br
.ti -1c
.RI "\fBverticalLayout_4\fP"
.br
.ti -1c
.RI "\fBcomboBox_options\fP"
.br
.ti -1c
.RI "\fBgroupBox_select_method\fP"
.br
.ti -1c
.RI "\fBverticalLayout_5\fP"
.br
.ti -1c
.RI "\fBcomboBox_method\fP"
.br
.ti -1c
.RI "\fBgroupBox_select_type\fP"
.br
.ti -1c
.RI "\fBverticalLayout_6\fP"
.br
.ti -1c
.RI "\fBcomboBox_type\fP"
.br
.ti -1c
.RI "\fBframe_6\fP"
.br
.ti -1c
.RI "\fBgridLayout\fP"
.br
.ti -1c
.RI "\fBpushButton\fP"
.br
.ti -1c
.RI "\fBpushButton_Export\fP"
.br
.ti -1c
.RI "\fBframe_4\fP"
.br
.ti -1c
.RI "\fBhorizontalLayout_4\fP"
.br
.ti -1c
.RI "\fBgroupBox_about\fP"
.br
.ti -1c
.RI "\fBlabel_info\fP"
.br
.ti -1c
.RI "\fBgroupBox_about_3\fP"
.br
.ti -1c
.RI "\fBlabel_label_info_result\fP"
.br
.ti -1c
.RI "\fBframe_5\fP"
.br
.ti -1c
.RI "\fBgroupBox_about_2\fP"
.br
.ti -1c
.RI "\fBlabel_info_option\fP"
.br
.ti -1c
.RI "\fBframe_8\fP"
.br
.ti -1c
.RI "\fBverticalLayout_7\fP"
.br
.ti -1c
.RI "\fBmenubar\fP"
.br
.ti -1c
.RI "\fBstatusbar\fP"
.br
.ti -1c
.RI "\fBfigure\fP"
.br
.ti -1c
.RI "\fBcanvas\fP"
.br
.ti -1c
.RI "\fBtoolbar\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "ui_mainwindow\&.Ui_MainWindow\&.retranslateUi ( self,  MainWindow)"

.SS "ui_mainwindow\&.Ui_MainWindow\&.setupUi ( self,  MainWindow)"

.SH "Member Data Documentation"
.PP 
.SS "ui_mainwindow\&.Ui_MainWindow\&.canvas"

.SS "ui_mainwindow\&.Ui_MainWindow\&.centralwidget"

.SS "ui_mainwindow\&.Ui_MainWindow\&.comboBox_camera"

.SS "ui_mainwindow\&.Ui_MainWindow\&.comboBox_method"

.SS "ui_mainwindow\&.Ui_MainWindow\&.comboBox_options"

.SS "ui_mainwindow\&.Ui_MainWindow\&.comboBox_type"

.SS "ui_mainwindow\&.Ui_MainWindow\&.dateEdit_from"

.SS "ui_mainwindow\&.Ui_MainWindow\&.dateEdit_to"

.SS "ui_mainwindow\&.Ui_MainWindow\&.figure"

.SS "ui_mainwindow\&.Ui_MainWindow\&.formLayout"

.SS "ui_mainwindow\&.Ui_MainWindow\&.formLayout_2"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_2"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_3"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_4"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_5"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_6"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_7"

.SS "ui_mainwindow\&.Ui_MainWindow\&.frame_8"

.SS "ui_mainwindow\&.Ui_MainWindow\&.gridLayout"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_about"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_about_2"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_about_3"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_options"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_period"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_selec_camera"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_select_method"

.SS "ui_mainwindow\&.Ui_MainWindow\&.groupBox_select_type"

.SS "ui_mainwindow\&.Ui_MainWindow\&.horizontalLayout"

.SS "ui_mainwindow\&.Ui_MainWindow\&.horizontalLayout_2"

.SS "ui_mainwindow\&.Ui_MainWindow\&.horizontalLayout_4"

.SS "ui_mainwindow\&.Ui_MainWindow\&.label_from"

.SS "ui_mainwindow\&.Ui_MainWindow\&.label_info"

.SS "ui_mainwindow\&.Ui_MainWindow\&.label_info_option"

.SS "ui_mainwindow\&.Ui_MainWindow\&.label_label_info_result"

.SS "ui_mainwindow\&.Ui_MainWindow\&.label_to"

.SS "ui_mainwindow\&.Ui_MainWindow\&.menubar"

.SS "ui_mainwindow\&.Ui_MainWindow\&.pushButton"

.SS "ui_mainwindow\&.Ui_MainWindow\&.pushButton_Export"

.SS "ui_mainwindow\&.Ui_MainWindow\&.statusbar"

.SS "ui_mainwindow\&.Ui_MainWindow\&.toolbar"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout_2"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout_3"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout_4"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout_5"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout_6"

.SS "ui_mainwindow\&.Ui_MainWindow\&.verticalLayout_7"


.SH "Author"
.PP 
Generated automatically by Doxygen for DAVA from the source code\&.
